### ISSUE TITLE
How await works. Support for async function

### ISSUE THREAD

**Issue by onmyway133** [malcommac/Hydra#1]
Hi, cool library 👍 

I was reading through https://github.com/malcommac/Hydra/blob/master/Sources/Hydra/Await.swift#L109

```swift
// Create a semaphore to block the execution of the flow until
		// the promise is fulfilled or rejected
		let semaphore = DispatchSemaphore(value: 0)
```

so we're turning async code -> sync code by blocking the current thread?

Also, it would be cooler if there's an example project 😉

**Comment by malcommac** [comment]
Hi, thank you. :)
Await is a way to block the execution of current caller thread, resolve passed promise in another queue then resume the execution. In fact you are telling "await the fulfill of a promise". Promise will be resolved in another thread but the queue called by await is blocked.
This allows you to express a sync code in a sync manner.
Howewer if you don't need it you can still use Promise in classic way.
I'll also add async shortcut soon.

**Comment by malcommac** [comment]
An example of await can be found in README. I'll make a project with examples later during development; meanwhile you can take a look at unit tests in order to see how it works.

**Comment by onmyway133** [comment]
@malcommac Hi, got it. Thanks 👍

**Comment by tomquist** [comment]
This should be mentioned in the README that await simply blocks the current thread. I first thought await magically worked similar to the C# await keyword and couldn't believe that this was even possible in Swift until I looked into the code to discover that it just blocks.

**Comment by onmyway133** [comment]
@tomquist yeah, I had the same thought too

**Comment by malcommac** [comment]
Yeah I think you are right; I've missed to explicitly add it to the documentation.
Here are the commits which fixes it https://github.com/malcommac/Hydra/commit/01ee6c576bfba7279cbba72252cbbcab38743d13 and https://github.com/malcommac/Hydra/commit/09a3afa73712f71bbd68cdc744baac3ee33cfe6d.

I've also added `async` operator which can works in two ways: to create a Promise or just execute a block of code.

I'm also looking a way to make it easier to write; if you have some suggestions I'll be more than happy to implement them.
