### ISSUE TITLE
Unable to run the `Promise.all` function.

### ISSUE THREAD

**Issue by ignazioc** [malcommac/Hydra#11]
the documentation says that the `all` function is a static function of the `Promise` class.

https://github.com/malcommac/Hydra#all

But I cannot find this function.
The `all` function seems to be a global function, that must be declared as `public` if is intended to be used from outside the framework.

**Comment by malcommac** [comment]
Ops you are right... I've missed that.
Added in https://github.com/malcommac/Hydra/commit/0e2f2914a1bbf687d727c11f4f72afcd92606441, it will be released with 0.9.2 later tomorrow.
Thank you!
