### ISSUE TITLE
Zip with promises array

### ISSUE THREAD

**Issue by fmo91** [malcommac/Hydra#2]
Hey, great library! I have been looking for something like this for a while.

I'd like to suggest that zip should receive an array of promises (if all of them shares the same return type) and a return a promise that combines all the inputs. It could also receive a reduce function as argument. What do you think? 

I mean something like this:

```swift
var promises = [Promise<User>]()

// Some code here. 

Promise.zip(promises)
      .then { (users: [User]) in 

      }
```

Thanks!

**Comment by malcommac** [comment]
Hi @fmo91 , thank you :)
I'm sorry but I think I don't really understand the request; sure I could introduce a zip operator with an array as input but why input array are promises? How you will combine them? Am I missing something? Can you provide to me an example of the usage.

**Comment by fallback** [comment]
I think, @fmo91 intends to describe the situation when, for example, you're going to load.. say, admin users with one promise, then managers with another promise. Type of result for both  is Promise<User>. And then, when all these promises are fulfilled, he want to get an array of User entities. 
From my personal side, I see no big reasons for this scenario, however, I might be useful for @fmo91 .

**Comment by fmo91** [comment]
Sorry for the late response. Yes, that's exactly what I'm describing. I have to upload images in base64 to the backend. I'm currently using RxSwift, so each upload returns an Observable, and then I use .zip to merge all these Observable and wait them to complete.
I believe a zip function that accepts an array of Promises in your case would be great. Or is there another way to do the same?

**Comment by malcommac** [comment]
You can create your promises and use `all` to execute all of them and wait for results.
However if one promise fails the entire chain also fail; is this the behaviour you need?

**Comment by malcommac** [comment]
Ping :)

**Comment by fmo91** [comment]
Yes, that's exactly what I was looking for. Thank you!

**Comment by malcommac** [comment]
U're welcome
