### ISSUE TITLE
Cancellable Promise

### ISSUE THREAD

**Issue by malcommac** [malcommac/Hydra#25]
I would to implement `cancel()` func in Hydra.
These days I'll investigate by looking at other libs implementations.
(@r-plus have you some advices?)

**Comment by r-plus** [comment]
I only know SwiftTask https://github.com/ReactKit/SwiftTask as cancellable promise library.

It provide task `configuration` object as promise closure parameter, that is detectable promise task chain already finished if cancelled as rejected. (but already started closure processing is not automatically stop, so users often check that parameter like NSOperation `isCancelled` property)

**Comment by 4ndrey** [comment]
@malcommac do you have any news regarding this feature?

**Comment by malcommac** [comment]
Hi guys,
I've worked on cancellable Promises support for Hydra.
In 0.9.7 branch you will found it (commit: https://github.com/malcommac/Hydra/commit/62bc119da3ef2e14aa0052d9ecd8e742101fb836).

Since there is no way to control the execution of the code of a Promise's body (and moreover it strictly depends of the business logic implemented by the developer) the best way IMHO to accomplish it is to delegate the responsibility and provide tools to accomplish this task in a safe manner.
The architecture uses the concept of Invalidation Tokens.

I've introduced a new protocol called `InvalidatableProtocol`; it has only a property called `isCancelled` which is a `Bool`: it will simply inform the Promise's body if the execution of the async task should be cancelled or not (there is also a concrete open class called `InvalidationToken` which implements the protocol).
You must to pass it at the init of the Promise object.
Into the body of the promise you must declare another type besides of `resolve` and `reject`: it's called `operation`; by checking the `operation.isCancelled` property you can decide if cancel the operation or not.

```swift
// In your async stuff you need to observer the isCancelled property
if operation.isCancelled { // someone outside the promise wanna cancel the operation
  // do our cleanup and stop our stuff (it depends your business logic)
  operation.cancel() // mark the promise as cancelled
  return // stop your code workflow
}
```

That's all.
This a complete example from the unit tests where a counter is stopped from the outside of the Promise.

```swift
func test_invalidationToken() {
  let invalidator: InvalidationToken = InvalidationToken()
  
  // it will stops our promise from the outside 2 seconds after the starts
  DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 2, execute: {
    invalidator.isCancelled = true
  })

  Promise<Int>(in: .main, token: token, { (resolve, reject, op) in
	var total: Int = 0
	for i in 0..<100 {
		if op.isCancelled == true {
			op.cancel()
			return
		}
		sleep(1)
		total += i
	}
	resolve(total)
	})
  }
```
