### ISSUE TITLE
How to use async function (example)

### ISSUE THREAD

**Issue by daviskoh** [malcommac/Hydra#37]
This will not run:

![image](https://user-images.githubusercontent.com/5395403/27261259-a29cd47e-540d-11e7-898c-202c1d9a7dee.png)

not even the print statement runs.

**This** however runs:

![image](https://user-images.githubusercontent.com/5395403/27261265-d2c9f1ea-540d-11e7-9f82-9085fc47d2d8.png)

Does the `async` func always need to be used in a chain using methods like `.always`? The README examples seem to show this is not needed, but I am confused about its actual usage.

NOTE: the `waitUntil` func is from [Nimble](https://github.com/Quick/Nimble)

Even if there was some sort of problem w/ the `waitUntil` func, shouldnt the 1st `print` statement at least execute before it timesout?

**Comment by daviskoh** [comment]
any updates???

**Comment by malcommac** [comment]
In `async` func you need to define and return the value you are expecting from promise and return it in sync/linear manner.
Let me show to you an example:

```swift
func test() {
		let _ = async { _ -> String in
			
			let r_1 = try await(self.async_getString())
			let r_2 = try await(self.async_concatenateString(val: r_1))
			return r_2
			}.then { result in
				print("result is \(result)")
			}.always(in: .main) {
				print("always made")
		}
	}
	
	func async_getString() -> Promise<String> {
		return Promise<String>({ r, rj, st in
			Thread.sleep(forTimeInterval: 2)
			r("hello")
		})
	}
	
	func async_concatenateString(val: String) -> Promise<String> {
		return Promise<String>({ r, rj, st in
			Thread.sleep(forTimeInterval: 2)
			r("\(val) world")
		})
	}
```

**Comment by daviskoh** [comment]
i see. so this from the docs:

```
async({
	print("And now some intensive task...")
	let result = try! await(.background, { resolve,reject, _ in
		delay(10, context: .background, closure: { // jut a trick for our example
			resolve(5)
		})
	})
	print("The result is \(result)")
})
```

would not be correct?
