### ISSUE TITLE
await does not work on ios11

### ISSUE THREAD

**Issue by hy9be** [malcommac/Hydra#42]
Hey I used to use ``await`` to queue up my task executions
``` swift
for a in self.aaa {
    try await(self.do[a].execute())
}
```
But I upgraded to ios 11 today and run into a EXC_BREAKPOINT here. The call stack is
![image](https://user-images.githubusercontent.com/3392907/28939909-e27e62a2-7860-11e7-9274-3335f017e772.png)

And the error is
![image](https://user-images.githubusercontent.com/3392907/28939935-f5f9646c-7860-11e7-9389-af4ec0c9cf3a.png)

**Comment by hy9be** [comment]
It has been fixed in AwaitKit: https://github.com/yannickl/AwaitKit/issues/17. What we need to do here is just upgrade to the newest release of it.

**Comment by hy9be** [comment]
@tcurdt I submitted a PR to fix it. Waiting for @malcommac to review.

**Comment by malcommac** [comment]
Added for 0.9.91 release. Thank you.

**Comment by paweljankowski** [comment]
@malcommac It seems this wasn't merged into `1.0.0` branch and not working correctly with Xcode 9 / iOS 10
