### ISSUE TITLE
.timeout operator keep Promise alive even if it resolves before it expires

### ISSUE THREAD

**Issue by mobilinked** [malcommac/Hydra#46]
Object will only be released (deinit) after the time interval of timeout setting. For example: 
.timeout(50)
.dosomething()

if all the work be done in 1 second, the object will be deinit after 50 seconds. 

Would you please help to check it?

**Comment by malcommac** [comment]
Thank you. I've checked with Profiler and it works fine now. Make a double check with your code.

My simple test is with:
```swift
self.testA().timeout(timeout: 15).then { v in
  print("\(v)")
}.catch { err in
  print("err")
}
	
func testA() -> Promise<String> {
	return Promise<String>({ (r, rj, st) in
		DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 5, execute: {
			r("resolves!")
		})
	})
}
```

**Comment by mobilinked** [comment]
Many thanks @malcommac 

I should were very careful to use class variable refrence when using it. I made a mistake like following the way: 

''' 
class manager {
      func doTest() {
           test().timeout(..)..... 
      }

      func test() -> Promise<Void> { (rosolved, _, _) in
             self.doSomething()
             resolved(()) 
      }
      
      func doSomething() { }
}
'''

As not using [weak self] in the func to construct promise object, it caused variable lock and ... 

Thanks for your support - this help me to know it's not caused by timeout directly.
