### ISSUE TITLE
Can't install using Carthage 

### ISSUE THREAD

**Issue by ivl** [malcommac/Hydra#51]
I am getting next errors 

*** Building scheme "Hydra-macOS" in Hydra.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'Hydra-macOS', module map will not be generated
warning: no umbrella header found for target 'Hydra-macOS', module map will not be generated
A shell task failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by ivl** [comment]
I have updated to Xcode 9. have another issue 

*** Building scheme "Hydra-macOS" in Hydra.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/ivl/work/newage/ada_mobile_assistant/ada_mobile_assistant/Carthage/Checkouts/Hydra/Sources/Hydra/Promise+Recover.swift:47:11: error: ambiguous reference to member 'then(in:_:)'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by malcommac** [comment]
Are you using 1.1.0 for a Swift 4.x project or 1.0.0 for a Swift 3 project?

**Comment by malcommac** [comment]
Fixed in 1.0.1 swift-3 branch and 1.2.0 for swift 4
thanks
