### ISSUE TITLE
Version 1.0.0 does not compile in Swift 3

### ISSUE THREAD

**Issue by leepfrog** [malcommac/Hydra#52]
I am currently unable to build Hydra 1.0.0 in Swift 3 for the MacOS target.

In `Promise+Recover.swift`, the recover method does not compile correctly because it is unable to resolve which `then` method to invoke.  The build error is: `/Hydra/Promise+Recover.swift:47:11: Ambiguous reference to member 'then(in:_:)'`

If you remove the lines: 
`
.cancelled(in: ctx, { _ -> Void in
				operation.cancel()
			})
`

then the swift compiler is able to resolve the appropriate `then` helper and the framework compiles.

**Comment by malcommac** [comment]
Fixed in 1.0.1.
See it on swift-3 branch https://github.com/malcommac/Hydra/tree/swift-3
