### ISSUE TITLE
'schedule(deadline:repeating:leeway:)' is unavailable in ios 11

### ISSUE THREAD

**Issue by Premal-Khetani** [malcommac/Hydra#53]
Hi,

I just run old code in with swift 3 xcode 9 with ios 11 and got below error : 

> `Pods/HydraAsync/Sources/Hydra/DispatchTimerWrapper.swift:46:9: 'schedule(deadline:repeating:leeway:)' is unavailable]`

Please suggest what to do? 

Thank you.

**Comment by malcommac** [comment]
Are you using 1.0.0 (Swift 3 compatible)
