### ISSUE TITLE
Adding support for delay parameter in retry operator

### ISSUE THREAD

**Issue by gloryluu** [malcommac/Hydra#71]
I think it would be helpful if this feature is available.

**Comment by malcommac** [comment]
`retry` operator now supports `delay` parameter starting from 2.0.4.  
This is an example:

```swift
func retry(_ attempts: Int = 3, delay: TimeInterval = 0,
               _ condition: @escaping ((Int, Error) throws -> Bool) = { _,_ in true }) { ... }
```

By default value is set to 0 (which means no delay) but you can set your own value expressed in seconds.
