### ISSUE TITLE
Build fail on Xcode 12 beta 2

### ISSUE THREAD

**Issue by MarcoCadei** [malcommac/Hydra#74]
When trying to build I get the following error in `Promise+Recover.swift`:
```
Cannot convert value of type 'Promise<Void>' to closure result type()'
```
It works fine on Xcode 11.5.

Version `1.2.1`

**Comment by malcommac** [comment]
2.0.3 is now available with fixes. Thanks.

**Comment by wish-hy** [comment]
This problem still exists in version 2.0.5
