### ISSUE TITLE
Hydra and iOS 9 compatibility

### ISSUE THREAD

**Issue by tuzaiz** [malcommac/Hydra#8]
Nice library! This is exactly what I'm looking for. But I got this error message when I tried to integrate it with my project (by Carthage).

```
Module file's minimum deployment target is ios10.2 v10.2: ./Carthage/Build/iOS/Hydra.framework/Modules/Hydra.swiftmodule/arm64.swiftmodule
```

**Comment by malcommac** [comment]
Take a test with 0.9.1.
It should be fixed now: 526d62f38f6c26fb70ce66f807eb411db6feba28
