### ISSUE TITLE
Since adding `[weak self]` in Promise+Recover with version 2.0.4 the promise lose the reference

### ISSUE THREAD

**Issue by cikpis** [malcommac/Hydra#83]
Hi @malcommac,

as the title, is that wanted?

**Comment by cikpis** [comment]
Because if I do this now the promise is never going to be executed 
```swift
func exec() -> Promise<Output> {
    Promise<Output> { _, _, _, in 
         // my code
    }.Recover{ _ in 
        // my code
    }
}

myObject.exec.then(in: .main) { _ in 
    / my code
}
```

**Comment by tuliot** [comment]
I'm having trouble with this as well. The `recover` block does not run for me in version 1.2.2. However, reversing the changes applied in https://github.com/malcommac/Hydra/commit/69a9213644ecb5a888870dc4777b78ff7d1283b2 fix the issue for me

**Comment by cikpis** [comment]
That's exactly what I did for now 😬
