### ISSUE TITLE
Deprecation of `await` keyword in Swift 5.4+. Using new Hydra.await()

### ISSUE THREAD

**Issue by danyf90** [malcommac/Hydra#86]
Ciao 👋 

As reported in the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes), the await keyword will start to emit warnings in Xcode 12.5:
```
Deprecations
The Swift compiler emits a warning for the use of the await keyword as an unqualified identifier. Wrap await with back-ticks so Swift always treats it as an identifier, or fully qualify declarations named await (for example, by adding self if it is a reference to an instance member named await from within the instance). (SE-0296, 67000350)
```

Is there any plan to address this in Hydra?

Thanks 🙌

**Comment by malcommac** [comment]
Hi,
I've moved the global `await` function into the `Hydra` namespace (within an enum).  
So you will need to call `try Hydra.await(...)` to suppress the warning.
The old `await` function is therefore deprecated. Thank you for your report. I'll publish 2.0.6 ASAP.
